apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: munji-back
  name: munji-back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: munji-back
  template:
    metadata:
      labels:
        app: munji-back
    spec:
      containers:
      - env:
        - name: HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: HIBERNATE_DDL_AUTO
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: SPRING_DATASOURCE_PASSWORD
        image: 320451040304.dkr.ecr.ap-northeast-2.amazonaws.com/munji-repo:ce2484ff5db17c9862e360efe1919eb96de24bdd
        name: munji-back
        ports:
        - containerPort: 8080
          name: munji-back
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 400m
      restartPolicy: Always
  revisionHistoryLimit: 3
