apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: munji-back
  name: munji-back
  namespace: munji
spec:
  replicas: 3
  selector:
    matchLabels:
      app: munji-back
  template:
    metadata:
      labels:
        app: munji-back
    spec:
      containers:
      - env:
        - name: HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: HIBERNATE_DDL_AUTO
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: DB_USER
        - name: KAKAO_API_KEY
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: KAKAO_API_KEY
        - name: OPEN_API_KEY
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: OPEN_API_KEY
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: DB_PW
        image: 320451040304.dkr.ecr.ap-northeast-2.amazonaws.com/munji-backend:94c56b6ebcd49d311b3d9798bff579c371d03ad5
        name: munji-back
        ports:
        - containerPort: 8080
          name: munji-back
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 300Mi
      restartPolicy: Always
  revisionHistoryLimit: 3
