apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: munji-back
  name: munji-back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: munji-back
  template:
    metadata:
      labels:
        app: munji-back
  revisionHistoryLimit: 3
    spec:
      containers:
      - env:
        - name: HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: HIBERNATE_DDL_AUTO
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: SPRING_DATASOURCE_PASSWORD
        image: oeckikekk/munjigoorm-back:b53a7c4eb14c7ad011ed7d0e04c0b0f62177b850
        name: munji-back
        ports:
        - containerPort: 8080
          name: munji-back
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 700m
      restartPolicy: Always
