apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: munji-front
  name: munji-front
  namespace: munji
spec:
  replicas: 3
  selector:
    matchLabels:
      app: munji-front
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: munji-front
    spec:
      containers:
      - name: munji-front
        image: 320451040304.dkr.ecr.ap-northeast-2.amazonaws.com/munji-frontend:45f1263b926231fc535a2e85edfe90e9e9993864
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 300m
            memory: 600Mi
          limits:
            cpu: 500m
            memory: 600Mi
      restartPolicy: Always
