apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: munji-front
  namespace: munji
  labels:
    app: munji-front
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: munji-front
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
status:
  currentReplicas: 0
  desiredReplicas: 3
