apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: munji-front
  name: munji-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: munji-front
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: munji-front
    spec:
      containers:
      - env:
        - name: REACT_APP_KAKAOMAP_API_KEY_JS
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: REACT_APP_KAKAOMAP_API_KEY_JS
        - name: REACT_APP_KAKAOMAP_API_KEY_REST
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: REACT_APP_KAKAOMAP_API_KEY_REST
        - name: REACT_APP_STATION_API_KEY
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: REACT_APP_STATION_API_KEY
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: munji-cm
              key: REACT_APP_BACKEND_URL
        image: oduodg/munji-frontend:dd21a1ed77b5239e241b0f6a62e8351418d103ad
        name: munji-front
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 400m
      restartPolicy: Always
