apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: munji-front
  name: munji-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: munji-front
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: munji-front
    spec:
      containers:
      - env:
        - name: REACT_APP_KAKAOMAP_API_KEY_JS
          valueFrom:
            secretKeyRef:
              name: munji-secret
              key: REACT_APP_KAKAOMAP_API_KEY_JS
        image: 320451040304.dkr.ecr.ap-northeast-2.amazonaws.com/munji-frontend:cc3387a837b32cc2e55ae0c6fdabd2f87a8ed3dc
        name: munji-front
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 400m
      restartPolicy: Always
