apiVersion: v1
kind: Pod
metadata:
  labels:
    app: py-day
  name: py-day
  namespace: munji
spec:
  containers:
  - image: 320451040304.dkr.ecr.ap-northeast-2.amazonaws.com/munji-database-day:f9ced917124eb97c7105642bca52dddd7e9578a0
    name: py-day
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_PORT
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_USER
    - name: DB_PW
      valueFrom:
        secretKeyRef:
          name: munji-secret
          key: DB_PW
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_NAME
  restartPolicy: OnFailure

