apiVersion: v1
kind: Pod
metadata:
  labels:
    app: py-once
  name: py-once
  namespace: munji
spec:
  containers:
  - image: 320451040304.dkr.ecr.ap-northeast-2.amazonaws.com/munji-database-once:2d7407ce8ddb89cb04169278260820f9e71a59ec
    name: py-once
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_PORT
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_USER
    - name: DB_PW
      valueFrom:
        secretKeyRef:
          name: munji-secret
          key: DB_PW
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_NAME
  restartPolicy: OnFailure
