apiVersion: v1
kind: Pod
metadata:
  labels:
    app: py-once
  name: py-once
spec:
  containers:
  - image: ksee1230/py:once-1.2
    name: py-once
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_PORT
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_USER
    - name: DB_PW
      valueFrom:
        secretKeyRef:
          name: munji-secret
          key: DB_PW
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: munji-cm
          key: DB_NAME
  restartPolicy: Never
