apiVersion: v1
kind: Secret
metadata:
  name: munji-secret
stringData:
  MYSQL_ROOT_PASSWORD: "1234"
  DB_PW: "1234"
  SPRING_DATASOURCE_PASSWORD: "1234"
  SPRING_DATASOURCE_PASSWORD: "1234"
  REACT_APP_KAKAOMAP_API_KEY_JS: "b1977047caf3a48ceeffdddf20869235"
  REACT_APP_KAKAOMAP_API_KEY_REST: "31d85bd8c34ef4e5581971efb0dbbb18"
  REACT_APP_STATION_API_KEY: "uXcXxgb4WIk2ccP87MzOmUMKgCP10jG5QSGOajTpCF42np8Yl0TZgiWjMDxC7EVxI7B/W0FU+yxw+rfSgLk1GQ=="

